version: '3'

services:
  flask:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "./src:/pj"
    tty: true
    environment:
      TZ: Asia/Tokyo
    command: export FLASK_APP=api-light; export FLASK_DEBUG=true; flask run --host 0.0.0.0 --port 8080
